# Generated by Django 2.2.4 on 2023-06-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('halls_app', '0002_remove_hall_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='user_booked',
            field=models.ManyToManyField(related_name='halls_booked', to='login_app.User'),
        ),
    ]
